// Code generated by go-mark-emoticon-gen, DO NOT EDIT.

package emoticon

import (
	"fmt"
)

type FaceType int16

const (
	UNKNOWN_Face              FaceType = -1  // "/unknown"
	U60CAU8BB6_Face           FaceType = 0   // "/惊讶"
	U6487U5634_Face           FaceType = 1   // "/撇嘴"
	U8272_Face                FaceType = 2   // "/色"
	U53D1U5446_Face           FaceType = 3   // "/发呆"
	U5F97U610F_Face           FaceType = 4   // "/得意"
	U6D41U6CEA_Face           FaceType = 5   // "/流泪"
	U5BB3U7F9E_Face           FaceType = 6   // "/害羞"
	U95EDU5634_Face           FaceType = 7   // "/闭嘴"
	U7761_Face                FaceType = 8   // "/睡"
	U5927U54ED_Face           FaceType = 9   // "/大哭"
	U5C34U5C2C_Face           FaceType = 10  // "/尴尬"
	U53D1U6012_Face           FaceType = 11  // "/发怒"
	U8C03U76AE_Face           FaceType = 12  // "/调皮"
	U5472U7259_Face           FaceType = 13  // "/呲牙"
	U5FAEU7B11_Face           FaceType = 14  // "/微笑"
	U96BEU8FC7_Face           FaceType = 15  // "/难过"
	U9177_Face                FaceType = 16  // "/酷"
	U6293U72C2_Face           FaceType = 18  // "/抓狂"
	U5410_Face                FaceType = 19  // "/吐"
	U5077U7B11_Face           FaceType = 20  // "/偷笑"
	U53EFU7231_Face           FaceType = 21  // "/可爱"
	U767DU773C_Face           FaceType = 22  // "/白眼"
	U50B2U6162_Face           FaceType = 23  // "/傲慢"
	U9965U997F_Face           FaceType = 24  // "/饥饿"
	U56F0_Face                FaceType = 25  // "/困"
	U60CAU6050_Face           FaceType = 26  // "/惊恐"
	U6D41U6C57_Face           FaceType = 27  // "/流汗"
	U61A8U7B11_Face           FaceType = 28  // "/憨笑"
	U60A0U95F2_Face           FaceType = 29  // "/悠闲"
	U594BU6597_Face           FaceType = 30  // "/奋斗"
	U5492U9A82_Face           FaceType = 31  // "/咒骂"
	U7591U95EE_Face           FaceType = 32  // "/疑问"
	U5618_Face                FaceType = 33  // "/嘘"
	U6655_Face                FaceType = 34  // "/晕"
	U6298U78E8_Face           FaceType = 35  // "/折磨"
	U8870_Face                FaceType = 36  // "/衰"
	U9AB7U9AC5_Face           FaceType = 37  // "/骷髅"
	U6572U6253_Face           FaceType = 38  // "/敲打"
	U518DU89C1_Face           FaceType = 39  // "/再见"
	U53D1U6296_Face           FaceType = 41  // "/发抖"
	U7231U60C5_Face           FaceType = 42  // "/爱情"
	U8DF3U8DF3_Face           FaceType = 43  // "/跳跳"
	U732AU5934_Face           FaceType = 46  // "/猪头"
	U62E5U62B1_Face           FaceType = 49  // "/拥抱"
	U86CBU7CD5_Face           FaceType = 53  // "/蛋糕"
	U95EAU7535_Face           FaceType = 54  // "/闪电"
	U70B8U5F39_Face           FaceType = 55  // "/炸弹"
	U5200_Face                FaceType = 56  // "/刀"
	U8DB3U7403_Face           FaceType = 57  // "/足球"
	U4FBFU4FBF_Face           FaceType = 59  // "/便便"
	U5496U5561_Face           FaceType = 60  // "/咖啡"
	U996D_Face                FaceType = 61  // "/饭"
	U73ABU7470_Face           FaceType = 63  // "/玫瑰"
	U51CBU8C22_Face           FaceType = 64  // "/凋谢"
	U7231U5FC3_Face           FaceType = 66  // "/爱心"
	U5FC3U788E_Face           FaceType = 67  // "/心碎"
	U793CU7269_Face           FaceType = 69  // "/礼物"
	U592AU9633_Face           FaceType = 74  // "/太阳"
	U6708U4EAE_Face           FaceType = 75  // "/月亮"
	U8D5E_Face                FaceType = 76  // "/赞"
	U8E29_Face                FaceType = 77  // "/踩"
	U63E1U624B_Face           FaceType = 78  // "/握手"
	U80DCU5229_Face           FaceType = 79  // "/胜利"
	U98DEU543B_Face           FaceType = 85  // "/飞吻"
	U6004U706B_Face           FaceType = 86  // "/怄火"
	U897FU74DC_Face           FaceType = 89  // "/西瓜"
	U51B7U6C57_Face           FaceType = 96  // "/冷汗"
	U64E6U6C57_Face           FaceType = 97  // "/擦汗"
	U62A0U9F3B_Face           FaceType = 98  // "/抠鼻"
	U9F13U638C_Face           FaceType = 99  // "/鼓掌"
	U7CD7U5927U4E86_Face      FaceType = 100 // "/糗大了"
	U574FU7B11_Face           FaceType = 101 // "/坏笑"
	U5DE6U54FCU54FC_Face      FaceType = 102 // "/左哼哼"
	U53F3U54FCU54FC_Face      FaceType = 103 // "/右哼哼"
	U54C8U6B20_Face           FaceType = 104 // "/哈欠"
	U9119U89C6_Face           FaceType = 105 // "/鄙视"
	U59D4U5C48_Face           FaceType = 106 // "/委屈"
	U5FEBU54EDU4E86_Face      FaceType = 107 // "/快哭了"
	U9634U9669_Face           FaceType = 108 // "/阴险"
	U5DE6U4EB2U4EB2_Face      FaceType = 109 // "/左亲亲"
	U5413_Face                FaceType = 110 // "/吓"
	U53EFU601C_Face           FaceType = 111 // "/可怜"
	U83DCU5200_Face           FaceType = 112 // "/菜刀"
	U5564U9152_Face           FaceType = 113 // "/啤酒"
	U7BEEU7403_Face           FaceType = 114 // "/篮球"
	U4E52U4E53_Face           FaceType = 115 // "/乒乓"
	U793AU7231_Face           FaceType = 116 // "/示爱"
	U74E2U866B_Face           FaceType = 117 // "/瓢虫"
	U62B1U62F3_Face           FaceType = 118 // "/抱拳"
	U52FEU5F15_Face           FaceType = 119 // "/勾引"
	U62F3U5934_Face           FaceType = 120 // "/拳头"
	U5DEEU52B2_Face           FaceType = 121 // "/差劲"
	U7231U4F60_Face           FaceType = 122 // "/爱你"
	NO_Face                   FaceType = 123 // "/NO"
	OK_Face                   FaceType = 124 // "/OK"
	U8F6CU5708_Face           FaceType = 125 // "/转圈"
	U78D5U5934_Face           FaceType = 126 // "/磕头"
	U56DEU5934_Face           FaceType = 127 // "/回头"
	U8DF3U7EF3_Face           FaceType = 128 // "/跳绳"
	U6325U624B_Face           FaceType = 129 // "/挥手"
	U6FC0U52A8_Face           FaceType = 130 // "/激动"
	U8857U821E_Face           FaceType = 131 // "/街舞"
	U732EU543B_Face           FaceType = 132 // "/献吻"
	U5DE6U592AU6781_Face      FaceType = 133 // "/左太极"
	U53F3U592AU6781_Face      FaceType = 134 // "/右太极"
	U53CCU559C_Face           FaceType = 136 // "/双喜"
	U97ADU70AE_Face           FaceType = 137 // "/鞭炮"
	U706FU7B3C_Face           FaceType = 138 // "/灯笼"
	KU6B4C_Face               FaceType = 140 // "/K歌"
	U559DU5F69_Face           FaceType = 144 // "/喝彩"
	U7948U7977_Face           FaceType = 145 // "/祈祷"
	U7206U7B4B_Face           FaceType = 146 // "/爆筋"
	U68D2U68D2U7CD6_Face      FaceType = 147 // "/棒棒糖"
	U559DU5976_Face           FaceType = 148 // "/喝奶"
	U98DEU673A_Face           FaceType = 151 // "/飞机"
	U949EU7968_Face           FaceType = 158 // "/钞票"
	U836F_Face                FaceType = 168 // "/药"
	U624BU67AA_Face           FaceType = 169 // "/手枪"
	U8336_Face                FaceType = 171 // "/茶"
	U7728U773CU775B_Face      FaceType = 172 // "/眨眼睛"
	U6CEAU5954_Face           FaceType = 173 // "/泪奔"
	U65E0U5948_Face           FaceType = 174 // "/无奈"
	U5356U840C_Face           FaceType = 175 // "/卖萌"
	U5C0FU7EA0U7ED3_Face      FaceType = 176 // "/小纠结"
	U55B7U8840_Face           FaceType = 177 // "/喷血"
	U659CU773CU7B11_Face      FaceType = 178 // "/斜眼笑"
	DOGE_Face                 FaceType = 179 // "/doge"
	U60CAU559C_Face           FaceType = 180 // "/惊喜"
	U9A9AU6270_Face           FaceType = 181 // "/骚扰"
	U7B11U54ED_Face           FaceType = 182 // "/笑哭"
	U6211U6700U7F8E_Face      FaceType = 183 // "/我最美"
	U6CB3U87F9_Face           FaceType = 184 // "/河蟹"
	U7F8AU9A7C_Face           FaceType = 185 // "/羊驼"
	U5E7DU7075_Face           FaceType = 187 // "/幽灵"
	U86CB_Face                FaceType = 188 // "/蛋"
	U83CAU82B1_Face           FaceType = 190 // "/菊花"
	U7EA2U5305_Face           FaceType = 192 // "/红包"
	U5927U7B11_Face           FaceType = 193 // "/大笑"
	U4E0DU5F00U5FC3_Face      FaceType = 194 // "/不开心"
	U51B7U6F20_Face           FaceType = 197 // "/冷漠"
	U5443_Face                FaceType = 198 // "/呃"
	U597DU68D2_Face           FaceType = 199 // "/好棒"
	U62DCU6258_Face           FaceType = 200 // "/拜托"
	U70B9U8D5E_Face           FaceType = 201 // "/点赞"
	U65E0U804A_Face           FaceType = 202 // "/无聊"
	U6258U8138_Face           FaceType = 203 // "/托脸"
	U5403_Face                FaceType = 204 // "/吃"
	U9001U82B1_Face           FaceType = 205 // "/送花"
	U5BB3U6015_Face           FaceType = 206 // "/害怕"
	U82B1U75F4_Face           FaceType = 207 // "/花痴"
	U5C0FU6837U513F_Face      FaceType = 208 // "/小样儿"
	U98D9U6CEA_Face           FaceType = 210 // "/飙泪"
	U6211U4E0DU770B_Face      FaceType = 211 // "/我不看"
	U6258U816E_Face           FaceType = 212 // "/托腮"
	U5575U5575_Face           FaceType = 214 // "/啵啵"
	U7CCAU8138_Face           FaceType = 215 // "/糊脸"
	U62CDU5934_Face           FaceType = 216 // "/拍头"
	U626FU4E00U626F_Face      FaceType = 217 // "/扯一扯"
	U8214U4E00U8214_Face      FaceType = 218 // "/舔一舔"
	U8E6DU4E00U8E6D_Face      FaceType = 219 // "/蹭一蹭"
	U62FDU70B8U5929_Face      FaceType = 220 // "/拽炸天"
	U9876U5471U5471_Face      FaceType = 221 // "/顶呱呱"
	U62B1U62B1_Face           FaceType = 222 // "/抱抱"
	U66B4U51FB_Face           FaceType = 223 // "/暴击"
	U5F00U67AA_Face           FaceType = 224 // "/开枪"
	U64A9U4E00U64A9_Face      FaceType = 225 // "/撩一撩"
	U62CDU684C_Face           FaceType = 226 // "/拍桌"
	U62CDU624B_Face           FaceType = 227 // "/拍手"
	U606DU559C_Face           FaceType = 228 // "/恭喜"
	U5E72U676F_Face           FaceType = 229 // "/干杯"
	U5632U8BBD_Face           FaceType = 230 // "/嘲讽"
	U54FC_Face                FaceType = 231 // "/哼"
	U4F5BU7CFB_Face           FaceType = 232 // "/佛系"
	U6390U4E00U6390_Face      FaceType = 233 // "/掐一掐"
	U60CAU5446_Face           FaceType = 234 // "/惊呆"
	U98A4U6296_Face           FaceType = 235 // "/颤抖"
	U5543U5934_Face           FaceType = 236 // "/啃头"
	U5077U770B_Face           FaceType = 237 // "/偷看"
	U6247U8138_Face           FaceType = 238 // "/扇脸"
	U539FU8C05_Face           FaceType = 239 // "/原谅"
	U55B7U8138_Face           FaceType = 240 // "/喷脸"
	U751FU65E5U5FEBU4E50_Face FaceType = 241 // "/生日快乐"
	U5934U649EU51FB_Face      FaceType = 242 // "/头撞击"
	U7529U5934_Face           FaceType = 243 // "/甩头"
	U6254U72D7_Face           FaceType = 244 // "/扔狗"
	U52A0U6CB9U5FC5U80DC_Face FaceType = 245 // "/加油必胜"
	U52A0U6CB9U62B1U62B1_Face FaceType = 246 // "/加油抱抱"
	U53E3U7F69U62A4U4F53_Face FaceType = 247 // "/口罩护体"
	U642CU7816U4E2D_Face      FaceType = 260 // "/搬砖中"
	U5FD9U5230U98DEU8D77_Face FaceType = 261 // "/忙到飞起"
	U8111U9614U75BC_Face      FaceType = 262 // "/脑阔疼"
	U6CA7U6851_Face           FaceType = 263 // "/沧桑"
	U6342U8138_Face           FaceType = 264 // "/捂脸"
	U8FA3U773CU775B_Face      FaceType = 265 // "/辣眼睛"
	U54E6U54DF_Face           FaceType = 266 // "/哦哟"
	U5934U79C3_Face           FaceType = 267 // "/头秃"
	U95EEU53F7U8138_Face      FaceType = 268 // "/问号脸"
	U6697U4E2DU89C2U5BDF_Face FaceType = 269 // "/暗中观察"
	EMM_Face                  FaceType = 270 // "/emm"
	U5403U74DC_Face           FaceType = 271 // "/吃瓜"
	U5475U5475U54D2_Face      FaceType = 272 // "/呵呵哒"
	U6211U9178U4E86_Face      FaceType = 273 // "/我酸了"
	U592AU5357U4E86_Face      FaceType = 274 // "/太南了"
	U8FA3U6912U9171_Face      FaceType = 276 // "/辣椒酱"
	U6C6AU6C6A_Face           FaceType = 277 // "/汪汪"
	U6C57_Face                FaceType = 278 // "/汗"
	U6253U8138_Face           FaceType = 279 // "/打脸"
	U51FBU638C_Face           FaceType = 280 // "/击掌"
	U65E0U773CU7B11_Face      FaceType = 281 // "/无眼笑"
	U656CU793C_Face           FaceType = 282 // "/敬礼"
	U72C2U7B11_Face           FaceType = 283 // "/狂笑"
	U9762U65E0U8868U60C5_Face FaceType = 284 // "/面无表情"
	U6478U9C7C_Face           FaceType = 285 // "/摸鱼"
	U9B54U9B3CU7B11_Face      FaceType = 286 // "/魔鬼笑"
	U54E6_Face                FaceType = 287 // "/哦"
	U8BF7_Face                FaceType = 288 // "/请"
	U7741U773C_Face           FaceType = 289 // "/睁眼"
	U6572U5F00U5FC3_Face      FaceType = 290 // "/敲开心"
	U9707U60CA_Face           FaceType = 291 // "/震惊"
	U8BA9U6211U5EB7U5EB7_Face FaceType = 292 // "/让我康康"
	U6478U9526U9CA4_Face      FaceType = 293 // "/摸锦鲤"
	U671FU5F85_Face           FaceType = 294 // "/期待"
	U62FFU5230U7EA2U5305_Face FaceType = 295 // "/拿到红包"
	U771FU597D_Face           FaceType = 296 // "/真好"
	U62DCU8C22_Face           FaceType = 297 // "/拜谢"
	U5143U5B9D_Face           FaceType = 298 // "/元宝"
	U725BU554A_Face           FaceType = 299 // "/牛啊"
	U80D6U4E09U65A4_Face      FaceType = 300 // "/胖三斤"
	U597DU95EA_Face           FaceType = 301 // "/好闪"
	U5DE6U62DCU5E74_Face      FaceType = 302 // "/左拜年"
	U53F3U62DCU5E74_Face      FaceType = 303 // "/右拜年"
	U7EA2U5305U5305_Face      FaceType = 304 // "/红包包"
	U53F3U4EB2U4EB2_Face      FaceType = 305 // "/右亲亲"
	U725BU6C14U51B2U5929_Face FaceType = 306 // "/牛气冲天"
	U55B5U55B5_Face           FaceType = 307 // "/喵喵"
	U6C42U7EA2U5305_Face      FaceType = 308 // "/求红包"
	U8C22U7EA2U5305_Face      FaceType = 309 // "/谢红包"
	U65B0U5E74U70DFU82B1_Face FaceType = 310 // "/新年烟花"
	U6253CALL_Face            FaceType = 311 // "/打call"
	U53D8U5F62_Face           FaceType = 312 // "/变形"
	U55D1U5230U4E86_Face      FaceType = 313 // "/嗑到了"
	U4ED4U7EC6U5206U6790_Face FaceType = 314 // "/仔细分析"
	U52A0U6CB9_Face           FaceType = 315 // "/加油"
	U6211U6CA1U4E8B_Face      FaceType = 316 // "/我没事"
	U83DCU6C6A_Face           FaceType = 317 // "/菜汪"
	U5D07U62DC_Face           FaceType = 318 // "/崇拜"
	U6BD4U5FC3_Face           FaceType = 319 // "/比心"
	U5E86U795D_Face           FaceType = 320 // "/庆祝"
	U8001U8272U75DE_Face      FaceType = 321 // "/老色痞"
	U62D2U7EDD_Face           FaceType = 322 // "/拒绝"
	U5ACCU5F03_Face           FaceType = 323 // "/嫌弃"
	U5403U7CD6_Face           FaceType = 324 // "/吃糖"
	U60CAU5413_Face           FaceType = 325 // "/惊吓"
	U751FU6C14_Face           FaceType = 326 // "/生气"
)

func (t FaceType) String() string {
	switch t {
	case UNKNOWN_Face:
		return "/unknown"
	case U60CAU8BB6_Face:
		return "/惊讶"
	case U6487U5634_Face:
		return "/撇嘴"
	case U8272_Face:
		return "/色"
	case U53D1U5446_Face:
		return "/发呆"
	case U5F97U610F_Face:
		return "/得意"
	case U6D41U6CEA_Face:
		return "/流泪"
	case U5BB3U7F9E_Face:
		return "/害羞"
	case U95EDU5634_Face:
		return "/闭嘴"
	case U7761_Face:
		return "/睡"
	case U5927U54ED_Face:
		return "/大哭"
	case U5C34U5C2C_Face:
		return "/尴尬"
	case U53D1U6012_Face:
		return "/发怒"
	case U8C03U76AE_Face:
		return "/调皮"
	case U5472U7259_Face:
		return "/呲牙"
	case U5FAEU7B11_Face:
		return "/微笑"
	case U96BEU8FC7_Face:
		return "/难过"
	case U9177_Face:
		return "/酷"
	case U6293U72C2_Face:
		return "/抓狂"
	case U5410_Face:
		return "/吐"
	case U5077U7B11_Face:
		return "/偷笑"
	case U53EFU7231_Face:
		return "/可爱"
	case U767DU773C_Face:
		return "/白眼"
	case U50B2U6162_Face:
		return "/傲慢"
	case U9965U997F_Face:
		return "/饥饿"
	case U56F0_Face:
		return "/困"
	case U60CAU6050_Face:
		return "/惊恐"
	case U6D41U6C57_Face:
		return "/流汗"
	case U61A8U7B11_Face:
		return "/憨笑"
	case U60A0U95F2_Face:
		return "/悠闲"
	case U594BU6597_Face:
		return "/奋斗"
	case U5492U9A82_Face:
		return "/咒骂"
	case U7591U95EE_Face:
		return "/疑问"
	case U5618_Face:
		return "/嘘"
	case U6655_Face:
		return "/晕"
	case U6298U78E8_Face:
		return "/折磨"
	case U8870_Face:
		return "/衰"
	case U9AB7U9AC5_Face:
		return "/骷髅"
	case U6572U6253_Face:
		return "/敲打"
	case U518DU89C1_Face:
		return "/再见"
	case U53D1U6296_Face:
		return "/发抖"
	case U7231U60C5_Face:
		return "/爱情"
	case U8DF3U8DF3_Face:
		return "/跳跳"
	case U732AU5934_Face:
		return "/猪头"
	case U62E5U62B1_Face:
		return "/拥抱"
	case U86CBU7CD5_Face:
		return "/蛋糕"
	case U95EAU7535_Face:
		return "/闪电"
	case U70B8U5F39_Face:
		return "/炸弹"
	case U5200_Face:
		return "/刀"
	case U8DB3U7403_Face:
		return "/足球"
	case U4FBFU4FBF_Face:
		return "/便便"
	case U5496U5561_Face:
		return "/咖啡"
	case U996D_Face:
		return "/饭"
	case U73ABU7470_Face:
		return "/玫瑰"
	case U51CBU8C22_Face:
		return "/凋谢"
	case U7231U5FC3_Face:
		return "/爱心"
	case U5FC3U788E_Face:
		return "/心碎"
	case U793CU7269_Face:
		return "/礼物"
	case U592AU9633_Face:
		return "/太阳"
	case U6708U4EAE_Face:
		return "/月亮"
	case U8D5E_Face:
		return "/赞"
	case U8E29_Face:
		return "/踩"
	case U63E1U624B_Face:
		return "/握手"
	case U80DCU5229_Face:
		return "/胜利"
	case U98DEU543B_Face:
		return "/飞吻"
	case U6004U706B_Face:
		return "/怄火"
	case U897FU74DC_Face:
		return "/西瓜"
	case U51B7U6C57_Face:
		return "/冷汗"
	case U64E6U6C57_Face:
		return "/擦汗"
	case U62A0U9F3B_Face:
		return "/抠鼻"
	case U9F13U638C_Face:
		return "/鼓掌"
	case U7CD7U5927U4E86_Face:
		return "/糗大了"
	case U574FU7B11_Face:
		return "/坏笑"
	case U5DE6U54FCU54FC_Face:
		return "/左哼哼"
	case U53F3U54FCU54FC_Face:
		return "/右哼哼"
	case U54C8U6B20_Face:
		return "/哈欠"
	case U9119U89C6_Face:
		return "/鄙视"
	case U59D4U5C48_Face:
		return "/委屈"
	case U5FEBU54EDU4E86_Face:
		return "/快哭了"
	case U9634U9669_Face:
		return "/阴险"
	case U5DE6U4EB2U4EB2_Face:
		return "/左亲亲"
	case U5413_Face:
		return "/吓"
	case U53EFU601C_Face:
		return "/可怜"
	case U83DCU5200_Face:
		return "/菜刀"
	case U5564U9152_Face:
		return "/啤酒"
	case U7BEEU7403_Face:
		return "/篮球"
	case U4E52U4E53_Face:
		return "/乒乓"
	case U793AU7231_Face:
		return "/示爱"
	case U74E2U866B_Face:
		return "/瓢虫"
	case U62B1U62F3_Face:
		return "/抱拳"
	case U52FEU5F15_Face:
		return "/勾引"
	case U62F3U5934_Face:
		return "/拳头"
	case U5DEEU52B2_Face:
		return "/差劲"
	case U7231U4F60_Face:
		return "/爱你"
	case NO_Face:
		return "/NO"
	case OK_Face:
		return "/OK"
	case U8F6CU5708_Face:
		return "/转圈"
	case U78D5U5934_Face:
		return "/磕头"
	case U56DEU5934_Face:
		return "/回头"
	case U8DF3U7EF3_Face:
		return "/跳绳"
	case U6325U624B_Face:
		return "/挥手"
	case U6FC0U52A8_Face:
		return "/激动"
	case U8857U821E_Face:
		return "/街舞"
	case U732EU543B_Face:
		return "/献吻"
	case U5DE6U592AU6781_Face:
		return "/左太极"
	case U53F3U592AU6781_Face:
		return "/右太极"
	case U53CCU559C_Face:
		return "/双喜"
	case U97ADU70AE_Face:
		return "/鞭炮"
	case U706FU7B3C_Face:
		return "/灯笼"
	case KU6B4C_Face:
		return "/K歌"
	case U559DU5F69_Face:
		return "/喝彩"
	case U7948U7977_Face:
		return "/祈祷"
	case U7206U7B4B_Face:
		return "/爆筋"
	case U68D2U68D2U7CD6_Face:
		return "/棒棒糖"
	case U559DU5976_Face:
		return "/喝奶"
	case U98DEU673A_Face:
		return "/飞机"
	case U949EU7968_Face:
		return "/钞票"
	case U836F_Face:
		return "/药"
	case U624BU67AA_Face:
		return "/手枪"
	case U8336_Face:
		return "/茶"
	case U7728U773CU775B_Face:
		return "/眨眼睛"
	case U6CEAU5954_Face:
		return "/泪奔"
	case U65E0U5948_Face:
		return "/无奈"
	case U5356U840C_Face:
		return "/卖萌"
	case U5C0FU7EA0U7ED3_Face:
		return "/小纠结"
	case U55B7U8840_Face:
		return "/喷血"
	case U659CU773CU7B11_Face:
		return "/斜眼笑"
	case DOGE_Face:
		return "/doge"
	case U60CAU559C_Face:
		return "/惊喜"
	case U9A9AU6270_Face:
		return "/骚扰"
	case U7B11U54ED_Face:
		return "/笑哭"
	case U6211U6700U7F8E_Face:
		return "/我最美"
	case U6CB3U87F9_Face:
		return "/河蟹"
	case U7F8AU9A7C_Face:
		return "/羊驼"
	case U5E7DU7075_Face:
		return "/幽灵"
	case U86CB_Face:
		return "/蛋"
	case U83CAU82B1_Face:
		return "/菊花"
	case U7EA2U5305_Face:
		return "/红包"
	case U5927U7B11_Face:
		return "/大笑"
	case U4E0DU5F00U5FC3_Face:
		return "/不开心"
	case U51B7U6F20_Face:
		return "/冷漠"
	case U5443_Face:
		return "/呃"
	case U597DU68D2_Face:
		return "/好棒"
	case U62DCU6258_Face:
		return "/拜托"
	case U70B9U8D5E_Face:
		return "/点赞"
	case U65E0U804A_Face:
		return "/无聊"
	case U6258U8138_Face:
		return "/托脸"
	case U5403_Face:
		return "/吃"
	case U9001U82B1_Face:
		return "/送花"
	case U5BB3U6015_Face:
		return "/害怕"
	case U82B1U75F4_Face:
		return "/花痴"
	case U5C0FU6837U513F_Face:
		return "/小样儿"
	case U98D9U6CEA_Face:
		return "/飙泪"
	case U6211U4E0DU770B_Face:
		return "/我不看"
	case U6258U816E_Face:
		return "/托腮"
	case U5575U5575_Face:
		return "/啵啵"
	case U7CCAU8138_Face:
		return "/糊脸"
	case U62CDU5934_Face:
		return "/拍头"
	case U626FU4E00U626F_Face:
		return "/扯一扯"
	case U8214U4E00U8214_Face:
		return "/舔一舔"
	case U8E6DU4E00U8E6D_Face:
		return "/蹭一蹭"
	case U62FDU70B8U5929_Face:
		return "/拽炸天"
	case U9876U5471U5471_Face:
		return "/顶呱呱"
	case U62B1U62B1_Face:
		return "/抱抱"
	case U66B4U51FB_Face:
		return "/暴击"
	case U5F00U67AA_Face:
		return "/开枪"
	case U64A9U4E00U64A9_Face:
		return "/撩一撩"
	case U62CDU684C_Face:
		return "/拍桌"
	case U62CDU624B_Face:
		return "/拍手"
	case U606DU559C_Face:
		return "/恭喜"
	case U5E72U676F_Face:
		return "/干杯"
	case U5632U8BBD_Face:
		return "/嘲讽"
	case U54FC_Face:
		return "/哼"
	case U4F5BU7CFB_Face:
		return "/佛系"
	case U6390U4E00U6390_Face:
		return "/掐一掐"
	case U60CAU5446_Face:
		return "/惊呆"
	case U98A4U6296_Face:
		return "/颤抖"
	case U5543U5934_Face:
		return "/啃头"
	case U5077U770B_Face:
		return "/偷看"
	case U6247U8138_Face:
		return "/扇脸"
	case U539FU8C05_Face:
		return "/原谅"
	case U55B7U8138_Face:
		return "/喷脸"
	case U751FU65E5U5FEBU4E50_Face:
		return "/生日快乐"
	case U5934U649EU51FB_Face:
		return "/头撞击"
	case U7529U5934_Face:
		return "/甩头"
	case U6254U72D7_Face:
		return "/扔狗"
	case U52A0U6CB9U5FC5U80DC_Face:
		return "/加油必胜"
	case U52A0U6CB9U62B1U62B1_Face:
		return "/加油抱抱"
	case U53E3U7F69U62A4U4F53_Face:
		return "/口罩护体"
	case U642CU7816U4E2D_Face:
		return "/搬砖中"
	case U5FD9U5230U98DEU8D77_Face:
		return "/忙到飞起"
	case U8111U9614U75BC_Face:
		return "/脑阔疼"
	case U6CA7U6851_Face:
		return "/沧桑"
	case U6342U8138_Face:
		return "/捂脸"
	case U8FA3U773CU775B_Face:
		return "/辣眼睛"
	case U54E6U54DF_Face:
		return "/哦哟"
	case U5934U79C3_Face:
		return "/头秃"
	case U95EEU53F7U8138_Face:
		return "/问号脸"
	case U6697U4E2DU89C2U5BDF_Face:
		return "/暗中观察"
	case EMM_Face:
		return "/emm"
	case U5403U74DC_Face:
		return "/吃瓜"
	case U5475U5475U54D2_Face:
		return "/呵呵哒"
	case U6211U9178U4E86_Face:
		return "/我酸了"
	case U592AU5357U4E86_Face:
		return "/太南了"
	case U8FA3U6912U9171_Face:
		return "/辣椒酱"
	case U6C6AU6C6A_Face:
		return "/汪汪"
	case U6C57_Face:
		return "/汗"
	case U6253U8138_Face:
		return "/打脸"
	case U51FBU638C_Face:
		return "/击掌"
	case U65E0U773CU7B11_Face:
		return "/无眼笑"
	case U656CU793C_Face:
		return "/敬礼"
	case U72C2U7B11_Face:
		return "/狂笑"
	case U9762U65E0U8868U60C5_Face:
		return "/面无表情"
	case U6478U9C7C_Face:
		return "/摸鱼"
	case U9B54U9B3CU7B11_Face:
		return "/魔鬼笑"
	case U54E6_Face:
		return "/哦"
	case U8BF7_Face:
		return "/请"
	case U7741U773C_Face:
		return "/睁眼"
	case U6572U5F00U5FC3_Face:
		return "/敲开心"
	case U9707U60CA_Face:
		return "/震惊"
	case U8BA9U6211U5EB7U5EB7_Face:
		return "/让我康康"
	case U6478U9526U9CA4_Face:
		return "/摸锦鲤"
	case U671FU5F85_Face:
		return "/期待"
	case U62FFU5230U7EA2U5305_Face:
		return "/拿到红包"
	case U771FU597D_Face:
		return "/真好"
	case U62DCU8C22_Face:
		return "/拜谢"
	case U5143U5B9D_Face:
		return "/元宝"
	case U725BU554A_Face:
		return "/牛啊"
	case U80D6U4E09U65A4_Face:
		return "/胖三斤"
	case U597DU95EA_Face:
		return "/好闪"
	case U5DE6U62DCU5E74_Face:
		return "/左拜年"
	case U53F3U62DCU5E74_Face:
		return "/右拜年"
	case U7EA2U5305U5305_Face:
		return "/红包包"
	case U53F3U4EB2U4EB2_Face:
		return "/右亲亲"
	case U725BU6C14U51B2U5929_Face:
		return "/牛气冲天"
	case U55B5U55B5_Face:
		return "/喵喵"
	case U6C42U7EA2U5305_Face:
		return "/求红包"
	case U8C22U7EA2U5305_Face:
		return "/谢红包"
	case U65B0U5E74U70DFU82B1_Face:
		return "/新年烟花"
	case U6253CALL_Face:
		return "/打call"
	case U53D8U5F62_Face:
		return "/变形"
	case U55D1U5230U4E86_Face:
		return "/嗑到了"
	case U4ED4U7EC6U5206U6790_Face:
		return "/仔细分析"
	case U52A0U6CB9_Face:
		return "/加油"
	case U6211U6CA1U4E8B_Face:
		return "/我没事"
	case U83DCU6C6A_Face:
		return "/菜汪"
	case U5D07U62DC_Face:
		return "/崇拜"
	case U6BD4U5FC3_Face:
		return "/比心"
	case U5E86U795D_Face:
		return "/庆祝"
	case U8001U8272U75DE_Face:
		return "/老色痞"
	case U62D2U7EDD_Face:
		return "/拒绝"
	case U5ACCU5F03_Face:
		return "/嫌弃"
	case U5403U7CD6_Face:
		return "/吃糖"
	case U60CAU5413_Face:
		return "/惊吓"
	case U751FU6C14_Face:
		return "/生气"
	}
	return "/unknown"
}

func ParseFaceType(s string) (FaceType, error) {
	switch s {
	case "/unknown":
		return UNKNOWN_Face, nil
	case "/惊讶":
		return U60CAU8BB6_Face, nil
	case "/撇嘴":
		return U6487U5634_Face, nil
	case "/色":
		return U8272_Face, nil
	case "/发呆":
		return U53D1U5446_Face, nil
	case "/得意":
		return U5F97U610F_Face, nil
	case "/流泪":
		return U6D41U6CEA_Face, nil
	case "/害羞":
		return U5BB3U7F9E_Face, nil
	case "/闭嘴":
		return U95EDU5634_Face, nil
	case "/睡":
		return U7761_Face, nil
	case "/大哭":
		return U5927U54ED_Face, nil
	case "/尴尬":
		return U5C34U5C2C_Face, nil
	case "/发怒":
		return U53D1U6012_Face, nil
	case "/调皮":
		return U8C03U76AE_Face, nil
	case "/呲牙":
		return U5472U7259_Face, nil
	case "/微笑":
		return U5FAEU7B11_Face, nil
	case "/难过":
		return U96BEU8FC7_Face, nil
	case "/酷":
		return U9177_Face, nil
	case "/抓狂":
		return U6293U72C2_Face, nil
	case "/吐":
		return U5410_Face, nil
	case "/偷笑":
		return U5077U7B11_Face, nil
	case "/可爱":
		return U53EFU7231_Face, nil
	case "/白眼":
		return U767DU773C_Face, nil
	case "/傲慢":
		return U50B2U6162_Face, nil
	case "/饥饿":
		return U9965U997F_Face, nil
	case "/困":
		return U56F0_Face, nil
	case "/惊恐":
		return U60CAU6050_Face, nil
	case "/流汗":
		return U6D41U6C57_Face, nil
	case "/憨笑":
		return U61A8U7B11_Face, nil
	case "/悠闲":
		return U60A0U95F2_Face, nil
	case "/奋斗":
		return U594BU6597_Face, nil
	case "/咒骂":
		return U5492U9A82_Face, nil
	case "/疑问":
		return U7591U95EE_Face, nil
	case "/嘘":
		return U5618_Face, nil
	case "/晕":
		return U6655_Face, nil
	case "/折磨":
		return U6298U78E8_Face, nil
	case "/衰":
		return U8870_Face, nil
	case "/骷髅":
		return U9AB7U9AC5_Face, nil
	case "/敲打":
		return U6572U6253_Face, nil
	case "/再见":
		return U518DU89C1_Face, nil
	case "/发抖":
		return U53D1U6296_Face, nil
	case "/爱情":
		return U7231U60C5_Face, nil
	case "/跳跳":
		return U8DF3U8DF3_Face, nil
	case "/猪头":
		return U732AU5934_Face, nil
	case "/拥抱":
		return U62E5U62B1_Face, nil
	case "/蛋糕":
		return U86CBU7CD5_Face, nil
	case "/闪电":
		return U95EAU7535_Face, nil
	case "/炸弹":
		return U70B8U5F39_Face, nil
	case "/刀":
		return U5200_Face, nil
	case "/足球":
		return U8DB3U7403_Face, nil
	case "/便便":
		return U4FBFU4FBF_Face, nil
	case "/咖啡":
		return U5496U5561_Face, nil
	case "/饭":
		return U996D_Face, nil
	case "/玫瑰":
		return U73ABU7470_Face, nil
	case "/凋谢":
		return U51CBU8C22_Face, nil
	case "/爱心":
		return U7231U5FC3_Face, nil
	case "/心碎":
		return U5FC3U788E_Face, nil
	case "/礼物":
		return U793CU7269_Face, nil
	case "/太阳":
		return U592AU9633_Face, nil
	case "/月亮":
		return U6708U4EAE_Face, nil
	case "/赞":
		return U8D5E_Face, nil
	case "/踩":
		return U8E29_Face, nil
	case "/握手":
		return U63E1U624B_Face, nil
	case "/胜利":
		return U80DCU5229_Face, nil
	case "/飞吻":
		return U98DEU543B_Face, nil
	case "/怄火":
		return U6004U706B_Face, nil
	case "/西瓜":
		return U897FU74DC_Face, nil
	case "/冷汗":
		return U51B7U6C57_Face, nil
	case "/擦汗":
		return U64E6U6C57_Face, nil
	case "/抠鼻":
		return U62A0U9F3B_Face, nil
	case "/鼓掌":
		return U9F13U638C_Face, nil
	case "/糗大了":
		return U7CD7U5927U4E86_Face, nil
	case "/坏笑":
		return U574FU7B11_Face, nil
	case "/左哼哼":
		return U5DE6U54FCU54FC_Face, nil
	case "/右哼哼":
		return U53F3U54FCU54FC_Face, nil
	case "/哈欠":
		return U54C8U6B20_Face, nil
	case "/鄙视":
		return U9119U89C6_Face, nil
	case "/委屈":
		return U59D4U5C48_Face, nil
	case "/快哭了":
		return U5FEBU54EDU4E86_Face, nil
	case "/阴险":
		return U9634U9669_Face, nil
	case "/左亲亲":
		return U5DE6U4EB2U4EB2_Face, nil
	case "/吓":
		return U5413_Face, nil
	case "/可怜":
		return U53EFU601C_Face, nil
	case "/菜刀":
		return U83DCU5200_Face, nil
	case "/啤酒":
		return U5564U9152_Face, nil
	case "/篮球":
		return U7BEEU7403_Face, nil
	case "/乒乓":
		return U4E52U4E53_Face, nil
	case "/示爱":
		return U793AU7231_Face, nil
	case "/瓢虫":
		return U74E2U866B_Face, nil
	case "/抱拳":
		return U62B1U62F3_Face, nil
	case "/勾引":
		return U52FEU5F15_Face, nil
	case "/拳头":
		return U62F3U5934_Face, nil
	case "/差劲":
		return U5DEEU52B2_Face, nil
	case "/爱你":
		return U7231U4F60_Face, nil
	case "/NO":
		return NO_Face, nil
	case "/OK":
		return OK_Face, nil
	case "/转圈":
		return U8F6CU5708_Face, nil
	case "/磕头":
		return U78D5U5934_Face, nil
	case "/回头":
		return U56DEU5934_Face, nil
	case "/跳绳":
		return U8DF3U7EF3_Face, nil
	case "/挥手":
		return U6325U624B_Face, nil
	case "/激动":
		return U6FC0U52A8_Face, nil
	case "/街舞":
		return U8857U821E_Face, nil
	case "/献吻":
		return U732EU543B_Face, nil
	case "/左太极":
		return U5DE6U592AU6781_Face, nil
	case "/右太极":
		return U53F3U592AU6781_Face, nil
	case "/双喜":
		return U53CCU559C_Face, nil
	case "/鞭炮":
		return U97ADU70AE_Face, nil
	case "/灯笼":
		return U706FU7B3C_Face, nil
	case "/K歌":
		return KU6B4C_Face, nil
	case "/喝彩":
		return U559DU5F69_Face, nil
	case "/祈祷":
		return U7948U7977_Face, nil
	case "/爆筋":
		return U7206U7B4B_Face, nil
	case "/棒棒糖":
		return U68D2U68D2U7CD6_Face, nil
	case "/喝奶":
		return U559DU5976_Face, nil
	case "/飞机":
		return U98DEU673A_Face, nil
	case "/钞票":
		return U949EU7968_Face, nil
	case "/药":
		return U836F_Face, nil
	case "/手枪":
		return U624BU67AA_Face, nil
	case "/茶":
		return U8336_Face, nil
	case "/眨眼睛":
		return U7728U773CU775B_Face, nil
	case "/泪奔":
		return U6CEAU5954_Face, nil
	case "/无奈":
		return U65E0U5948_Face, nil
	case "/卖萌":
		return U5356U840C_Face, nil
	case "/小纠结":
		return U5C0FU7EA0U7ED3_Face, nil
	case "/喷血":
		return U55B7U8840_Face, nil
	case "/斜眼笑":
		return U659CU773CU7B11_Face, nil
	case "/doge":
		return DOGE_Face, nil
	case "/惊喜":
		return U60CAU559C_Face, nil
	case "/骚扰":
		return U9A9AU6270_Face, nil
	case "/笑哭":
		return U7B11U54ED_Face, nil
	case "/我最美":
		return U6211U6700U7F8E_Face, nil
	case "/河蟹":
		return U6CB3U87F9_Face, nil
	case "/羊驼":
		return U7F8AU9A7C_Face, nil
	case "/幽灵":
		return U5E7DU7075_Face, nil
	case "/蛋":
		return U86CB_Face, nil
	case "/菊花":
		return U83CAU82B1_Face, nil
	case "/红包":
		return U7EA2U5305_Face, nil
	case "/大笑":
		return U5927U7B11_Face, nil
	case "/不开心":
		return U4E0DU5F00U5FC3_Face, nil
	case "/冷漠":
		return U51B7U6F20_Face, nil
	case "/呃":
		return U5443_Face, nil
	case "/好棒":
		return U597DU68D2_Face, nil
	case "/拜托":
		return U62DCU6258_Face, nil
	case "/点赞":
		return U70B9U8D5E_Face, nil
	case "/无聊":
		return U65E0U804A_Face, nil
	case "/托脸":
		return U6258U8138_Face, nil
	case "/吃":
		return U5403_Face, nil
	case "/送花":
		return U9001U82B1_Face, nil
	case "/害怕":
		return U5BB3U6015_Face, nil
	case "/花痴":
		return U82B1U75F4_Face, nil
	case "/小样儿":
		return U5C0FU6837U513F_Face, nil
	case "/飙泪":
		return U98D9U6CEA_Face, nil
	case "/我不看":
		return U6211U4E0DU770B_Face, nil
	case "/托腮":
		return U6258U816E_Face, nil
	case "/啵啵":
		return U5575U5575_Face, nil
	case "/糊脸":
		return U7CCAU8138_Face, nil
	case "/拍头":
		return U62CDU5934_Face, nil
	case "/扯一扯":
		return U626FU4E00U626F_Face, nil
	case "/舔一舔":
		return U8214U4E00U8214_Face, nil
	case "/蹭一蹭":
		return U8E6DU4E00U8E6D_Face, nil
	case "/拽炸天":
		return U62FDU70B8U5929_Face, nil
	case "/顶呱呱":
		return U9876U5471U5471_Face, nil
	case "/抱抱":
		return U62B1U62B1_Face, nil
	case "/暴击":
		return U66B4U51FB_Face, nil
	case "/开枪":
		return U5F00U67AA_Face, nil
	case "/撩一撩":
		return U64A9U4E00U64A9_Face, nil
	case "/拍桌":
		return U62CDU684C_Face, nil
	case "/拍手":
		return U62CDU624B_Face, nil
	case "/恭喜":
		return U606DU559C_Face, nil
	case "/干杯":
		return U5E72U676F_Face, nil
	case "/嘲讽":
		return U5632U8BBD_Face, nil
	case "/哼":
		return U54FC_Face, nil
	case "/佛系":
		return U4F5BU7CFB_Face, nil
	case "/掐一掐":
		return U6390U4E00U6390_Face, nil
	case "/惊呆":
		return U60CAU5446_Face, nil
	case "/颤抖":
		return U98A4U6296_Face, nil
	case "/啃头":
		return U5543U5934_Face, nil
	case "/偷看":
		return U5077U770B_Face, nil
	case "/扇脸":
		return U6247U8138_Face, nil
	case "/原谅":
		return U539FU8C05_Face, nil
	case "/喷脸":
		return U55B7U8138_Face, nil
	case "/生日快乐":
		return U751FU65E5U5FEBU4E50_Face, nil
	case "/头撞击":
		return U5934U649EU51FB_Face, nil
	case "/甩头":
		return U7529U5934_Face, nil
	case "/扔狗":
		return U6254U72D7_Face, nil
	case "/加油必胜":
		return U52A0U6CB9U5FC5U80DC_Face, nil
	case "/加油抱抱":
		return U52A0U6CB9U62B1U62B1_Face, nil
	case "/口罩护体":
		return U53E3U7F69U62A4U4F53_Face, nil
	case "/搬砖中":
		return U642CU7816U4E2D_Face, nil
	case "/忙到飞起":
		return U5FD9U5230U98DEU8D77_Face, nil
	case "/脑阔疼":
		return U8111U9614U75BC_Face, nil
	case "/沧桑":
		return U6CA7U6851_Face, nil
	case "/捂脸":
		return U6342U8138_Face, nil
	case "/辣眼睛":
		return U8FA3U773CU775B_Face, nil
	case "/哦哟":
		return U54E6U54DF_Face, nil
	case "/头秃":
		return U5934U79C3_Face, nil
	case "/问号脸":
		return U95EEU53F7U8138_Face, nil
	case "/暗中观察":
		return U6697U4E2DU89C2U5BDF_Face, nil
	case "/emm":
		return EMM_Face, nil
	case "/吃瓜":
		return U5403U74DC_Face, nil
	case "/呵呵哒":
		return U5475U5475U54D2_Face, nil
	case "/我酸了":
		return U6211U9178U4E86_Face, nil
	case "/太南了":
		return U592AU5357U4E86_Face, nil
	case "/辣椒酱":
		return U8FA3U6912U9171_Face, nil
	case "/汪汪":
		return U6C6AU6C6A_Face, nil
	case "/汗":
		return U6C57_Face, nil
	case "/打脸":
		return U6253U8138_Face, nil
	case "/击掌":
		return U51FBU638C_Face, nil
	case "/无眼笑":
		return U65E0U773CU7B11_Face, nil
	case "/敬礼":
		return U656CU793C_Face, nil
	case "/狂笑":
		return U72C2U7B11_Face, nil
	case "/面无表情":
		return U9762U65E0U8868U60C5_Face, nil
	case "/摸鱼":
		return U6478U9C7C_Face, nil
	case "/魔鬼笑":
		return U9B54U9B3CU7B11_Face, nil
	case "/哦":
		return U54E6_Face, nil
	case "/请":
		return U8BF7_Face, nil
	case "/睁眼":
		return U7741U773C_Face, nil
	case "/敲开心":
		return U6572U5F00U5FC3_Face, nil
	case "/震惊":
		return U9707U60CA_Face, nil
	case "/让我康康":
		return U8BA9U6211U5EB7U5EB7_Face, nil
	case "/摸锦鲤":
		return U6478U9526U9CA4_Face, nil
	case "/期待":
		return U671FU5F85_Face, nil
	case "/拿到红包":
		return U62FFU5230U7EA2U5305_Face, nil
	case "/真好":
		return U771FU597D_Face, nil
	case "/拜谢":
		return U62DCU8C22_Face, nil
	case "/元宝":
		return U5143U5B9D_Face, nil
	case "/牛啊":
		return U725BU554A_Face, nil
	case "/胖三斤":
		return U80D6U4E09U65A4_Face, nil
	case "/好闪":
		return U597DU95EA_Face, nil
	case "/左拜年":
		return U5DE6U62DCU5E74_Face, nil
	case "/右拜年":
		return U53F3U62DCU5E74_Face, nil
	case "/红包包":
		return U7EA2U5305U5305_Face, nil
	case "/右亲亲":
		return U53F3U4EB2U4EB2_Face, nil
	case "/牛气冲天":
		return U725BU6C14U51B2U5929_Face, nil
	case "/喵喵":
		return U55B5U55B5_Face, nil
	case "/求红包":
		return U6C42U7EA2U5305_Face, nil
	case "/谢红包":
		return U8C22U7EA2U5305_Face, nil
	case "/新年烟花":
		return U65B0U5E74U70DFU82B1_Face, nil
	case "/打call":
		return U6253CALL_Face, nil
	case "/变形":
		return U53D8U5F62_Face, nil
	case "/嗑到了":
		return U55D1U5230U4E86_Face, nil
	case "/仔细分析":
		return U4ED4U7EC6U5206U6790_Face, nil
	case "/加油":
		return U52A0U6CB9_Face, nil
	case "/我没事":
		return U6211U6CA1U4E8B_Face, nil
	case "/菜汪":
		return U83DCU6C6A_Face, nil
	case "/崇拜":
		return U5D07U62DC_Face, nil
	case "/比心":
		return U6BD4U5FC3_Face, nil
	case "/庆祝":
		return U5E86U795D_Face, nil
	case "/老色痞":
		return U8001U8272U75DE_Face, nil
	case "/拒绝":
		return U62D2U7EDD_Face, nil
	case "/嫌弃":
		return U5ACCU5F03_Face, nil
	case "/吃糖":
		return U5403U7CD6_Face, nil
	case "/惊吓":
		return U60CAU5413_Face, nil
	case "/生气":
		return U751FU6C14_Face, nil
	}
	return UNKNOWN_Face, fmt.Errorf("Unknown Face String: '%s', defaulting to UNKNOWN_Face", s)
}
