// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: cmd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cmd0X0388Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetType        int32                    `protobuf:"varint,1,opt,name=net_type,json=netType,proto3" json:"net_type,omitempty"`
	SubCmd         int32                    `protobuf:"varint,2,opt,name=sub_cmd,json=subCmd,proto3" json:"sub_cmd,omitempty"`
	TryUploadImage []*TryUploadImageRequest `protobuf:"bytes,3,rep,name=try_upload_image,json=tryUploadImage,proto3" json:"try_upload_image,omitempty"`
	GetImageUrl    []*GetImageURLRequest    `protobuf:"bytes,4,rep,name=get_image_url,json=getImageUrl,proto3" json:"get_image_url,omitempty"`
	TryUploadPtt   []*TryUploadPTTRequest   `protobuf:"bytes,5,rep,name=try_upload_ptt,json=tryUploadPtt,proto3" json:"try_upload_ptt,omitempty"`
	GetPttUrl      []*GetPTTURLRequest      `protobuf:"bytes,6,rep,name=get_ptt_url,json=getPttUrl,proto3" json:"get_ptt_url,omitempty"`
	CommandId      int32                    `protobuf:"varint,7,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	DelImage       []*DeleteImageRequest    `protobuf:"bytes,8,rep,name=del_image,json=delImage,proto3" json:"del_image,omitempty"`
	Extension      []byte                   `protobuf:"bytes,9,opt,name=extension,proto3" json:"extension,omitempty"`
}

func (x *Cmd0X0388Request) Reset() {
	*x = Cmd0X0388Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cmd0X0388Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cmd0X0388Request) ProtoMessage() {}

func (x *Cmd0X0388Request) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cmd0X0388Request.ProtoReflect.Descriptor instead.
func (*Cmd0X0388Request) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{0}
}

func (x *Cmd0X0388Request) GetNetType() int32 {
	if x != nil {
		return x.NetType
	}
	return 0
}

func (x *Cmd0X0388Request) GetSubCmd() int32 {
	if x != nil {
		return x.SubCmd
	}
	return 0
}

func (x *Cmd0X0388Request) GetTryUploadImage() []*TryUploadImageRequest {
	if x != nil {
		return x.TryUploadImage
	}
	return nil
}

func (x *Cmd0X0388Request) GetGetImageUrl() []*GetImageURLRequest {
	if x != nil {
		return x.GetImageUrl
	}
	return nil
}

func (x *Cmd0X0388Request) GetTryUploadPtt() []*TryUploadPTTRequest {
	if x != nil {
		return x.TryUploadPtt
	}
	return nil
}

func (x *Cmd0X0388Request) GetGetPttUrl() []*GetPTTURLRequest {
	if x != nil {
		return x.GetPttUrl
	}
	return nil
}

func (x *Cmd0X0388Request) GetCommandId() int32 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *Cmd0X0388Request) GetDelImage() []*DeleteImageRequest {
	if x != nil {
		return x.DelImage
	}
	return nil
}

func (x *Cmd0X0388Request) GetExtension() []byte {
	if x != nil {
		return x.Extension
	}
	return nil
}

type Cmd0X0388Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientIp       int32                     `protobuf:"varint,1,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	SubCmd         int32                     `protobuf:"varint,2,opt,name=sub_cmd,json=subCmd,proto3" json:"sub_cmd,omitempty"`
	TryUploadImage []*TryUploadImageResponse `protobuf:"bytes,3,rep,name=try_upload_image,json=tryUploadImage,proto3" json:"try_upload_image,omitempty"`
	GetImageUrl    []*GetImageURLResponse    `protobuf:"bytes,4,rep,name=get_image_url,json=getImageUrl,proto3" json:"get_image_url,omitempty"`
	TryUploadPtt   []*TryUploadPTTResponse   `protobuf:"bytes,5,rep,name=try_upload_ptt,json=tryUploadPtt,proto3" json:"try_upload_ptt,omitempty"`
	GetPttUrl      []*GetPTTURLResponse      `protobuf:"bytes,6,rep,name=get_ptt_url,json=getPttUrl,proto3" json:"get_ptt_url,omitempty"`
	DelImage       []*DeleteImageResponse    `protobuf:"bytes,7,rep,name=del_image,json=delImage,proto3" json:"del_image,omitempty"`
}

func (x *Cmd0X0388Response) Reset() {
	*x = Cmd0X0388Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cmd0X0388Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cmd0X0388Response) ProtoMessage() {}

func (x *Cmd0X0388Response) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cmd0X0388Response.ProtoReflect.Descriptor instead.
func (*Cmd0X0388Response) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{1}
}

func (x *Cmd0X0388Response) GetClientIp() int32 {
	if x != nil {
		return x.ClientIp
	}
	return 0
}

func (x *Cmd0X0388Response) GetSubCmd() int32 {
	if x != nil {
		return x.SubCmd
	}
	return 0
}

func (x *Cmd0X0388Response) GetTryUploadImage() []*TryUploadImageResponse {
	if x != nil {
		return x.TryUploadImage
	}
	return nil
}

func (x *Cmd0X0388Response) GetGetImageUrl() []*GetImageURLResponse {
	if x != nil {
		return x.GetImageUrl
	}
	return nil
}

func (x *Cmd0X0388Response) GetTryUploadPtt() []*TryUploadPTTResponse {
	if x != nil {
		return x.TryUploadPtt
	}
	return nil
}

func (x *Cmd0X0388Response) GetGetPttUrl() []*GetPTTURLResponse {
	if x != nil {
		return x.GetPttUrl
	}
	return nil
}

func (x *Cmd0X0388Response) GetDelImage() []*DeleteImageResponse {
	if x != nil {
		return x.DelImage
	}
	return nil
}

type DeleteImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteImageRequest) Reset() {
	*x = DeleteImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteImageRequest) ProtoMessage() {}

func (x *DeleteImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteImageRequest.ProtoReflect.Descriptor instead.
func (*DeleteImageRequest) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{2}
}

type DeleteImageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteImageResponse) Reset() {
	*x = DeleteImageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteImageResponse) ProtoMessage() {}

func (x *DeleteImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteImageResponse.ProtoReflect.Descriptor instead.
func (*DeleteImageResponse) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{3}
}

type GetImageURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetImageURLRequest) Reset() {
	*x = GetImageURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetImageURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageURLRequest) ProtoMessage() {}

func (x *GetImageURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageURLRequest.ProtoReflect.Descriptor instead.
func (*GetImageURLRequest) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{4}
}

type GetImageURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetImageURLResponse) Reset() {
	*x = GetImageURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetImageURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageURLResponse) ProtoMessage() {}

func (x *GetImageURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageURLResponse.ProtoReflect.Descriptor instead.
func (*GetImageURLResponse) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{5}
}

type GetPTTURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPTTURLRequest) Reset() {
	*x = GetPTTURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPTTURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPTTURLRequest) ProtoMessage() {}

func (x *GetPTTURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPTTURLRequest.ProtoReflect.Descriptor instead.
func (*GetPTTURLRequest) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{6}
}

type GetPTTURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPTTURLResponse) Reset() {
	*x = GetPTTURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPTTURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPTTURLResponse) ProtoMessage() {}

func (x *GetPTTURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPTTURLResponse.ProtoReflect.Descriptor instead.
func (*GetPTTURLResponse) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{7}
}

type ImageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileMd5    []byte `protobuf:"bytes,1,opt,name=file_md5,json=fileMd5,proto3" json:"file_md5,omitempty"`
	FileType   int32  `protobuf:"varint,2,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	FileSize   int64  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileWidth  int32  `protobuf:"varint,4,opt,name=file_width,json=fileWidth,proto3" json:"file_width,omitempty"`
	FileHeight int32  `protobuf:"varint,5,opt,name=file_height,json=fileHeight,proto3" json:"file_height,omitempty"`
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{8}
}

func (x *ImageInfo) GetFileMd5() []byte {
	if x != nil {
		return x.FileMd5
	}
	return nil
}

func (x *ImageInfo) GetFileType() int32 {
	if x != nil {
		return x.FileType
	}
	return 0
}

func (x *ImageInfo) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ImageInfo) GetFileWidth() int32 {
	if x != nil {
		return x.FileWidth
	}
	return 0
}

func (x *ImageInfo) GetFileHeight() int32 {
	if x != nil {
		return x.FileHeight
	}
	return 0
}

type IPv6Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip6  []byte `protobuf:"bytes,1,opt,name=ip6,proto3" json:"ip6,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *IPv6Info) Reset() {
	*x = IPv6Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPv6Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPv6Info) ProtoMessage() {}

func (x *IPv6Info) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPv6Info.ProtoReflect.Descriptor instead.
func (*IPv6Info) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{9}
}

func (x *IPv6Info) GetIp6() []byte {
	if x != nil {
		return x.Ip6
	}
	return nil
}

func (x *IPv6Info) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type TryUploadImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupCode       int64  `protobuf:"varint,1,opt,name=group_code,json=groupCode,proto3" json:"group_code,omitempty"`
	SrcUin          int64  `protobuf:"varint,2,opt,name=src_uin,json=srcUin,proto3" json:"src_uin,omitempty"`
	FileId          int64  `protobuf:"varint,3,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileMd5         []byte `protobuf:"bytes,4,opt,name=file_md5,json=fileMd5,proto3" json:"file_md5,omitempty"`
	FileSize        int64  `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Filename        string `protobuf:"bytes,6,opt,name=filename,proto3" json:"filename,omitempty"`
	SrcTerm         int32  `protobuf:"varint,7,opt,name=src_term,json=srcTerm,proto3" json:"src_term,omitempty"`
	PlatformType    int32  `protobuf:"varint,8,opt,name=platform_type,json=platformType,proto3" json:"platform_type,omitempty"`
	BuType          int32  `protobuf:"varint,9,opt,name=bu_type,json=buType,proto3" json:"bu_type,omitempty"`
	PictureWidth    int32  `protobuf:"varint,10,opt,name=picture_width,json=pictureWidth,proto3" json:"picture_width,omitempty"`
	PictureHeight   int32  `protobuf:"varint,11,opt,name=picture_height,json=pictureHeight,proto3" json:"picture_height,omitempty"`
	PictureType     int32  `protobuf:"varint,12,opt,name=picture_type,json=pictureType,proto3" json:"picture_type,omitempty"`
	BuildVersion    string `protobuf:"bytes,13,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	InnerIp         int32  `protobuf:"varint,14,opt,name=inner_ip,json=innerIp,proto3" json:"inner_ip,omitempty"`
	AppPictureType  int32  `protobuf:"varint,15,opt,name=app_picture_type,json=appPictureType,proto3" json:"app_picture_type,omitempty"`
	OriginalPicture int32  `protobuf:"varint,16,opt,name=original_picture,json=originalPicture,proto3" json:"original_picture,omitempty"`
	FileIndex       []byte `protobuf:"bytes,17,opt,name=file_index,json=fileIndex,proto3" json:"file_index,omitempty"`
	DstUin          int64  `protobuf:"varint,18,opt,name=dst_uin,json=dstUin,proto3" json:"dst_uin,omitempty"`
	ServerUpload    int32  `protobuf:"varint,19,opt,name=server_upload,json=serverUpload,proto3" json:"server_upload,omitempty"`
	TransferUrl     string `protobuf:"bytes,20,opt,name=transfer_url,json=transferUrl,proto3" json:"transfer_url,omitempty"`
}

func (x *TryUploadImageRequest) Reset() {
	*x = TryUploadImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TryUploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryUploadImageRequest) ProtoMessage() {}

func (x *TryUploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryUploadImageRequest.ProtoReflect.Descriptor instead.
func (*TryUploadImageRequest) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{10}
}

func (x *TryUploadImageRequest) GetGroupCode() int64 {
	if x != nil {
		return x.GroupCode
	}
	return 0
}

func (x *TryUploadImageRequest) GetSrcUin() int64 {
	if x != nil {
		return x.SrcUin
	}
	return 0
}

func (x *TryUploadImageRequest) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *TryUploadImageRequest) GetFileMd5() []byte {
	if x != nil {
		return x.FileMd5
	}
	return nil
}

func (x *TryUploadImageRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *TryUploadImageRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *TryUploadImageRequest) GetSrcTerm() int32 {
	if x != nil {
		return x.SrcTerm
	}
	return 0
}

func (x *TryUploadImageRequest) GetPlatformType() int32 {
	if x != nil {
		return x.PlatformType
	}
	return 0
}

func (x *TryUploadImageRequest) GetBuType() int32 {
	if x != nil {
		return x.BuType
	}
	return 0
}

func (x *TryUploadImageRequest) GetPictureWidth() int32 {
	if x != nil {
		return x.PictureWidth
	}
	return 0
}

func (x *TryUploadImageRequest) GetPictureHeight() int32 {
	if x != nil {
		return x.PictureHeight
	}
	return 0
}

func (x *TryUploadImageRequest) GetPictureType() int32 {
	if x != nil {
		return x.PictureType
	}
	return 0
}

func (x *TryUploadImageRequest) GetBuildVersion() string {
	if x != nil {
		return x.BuildVersion
	}
	return ""
}

func (x *TryUploadImageRequest) GetInnerIp() int32 {
	if x != nil {
		return x.InnerIp
	}
	return 0
}

func (x *TryUploadImageRequest) GetAppPictureType() int32 {
	if x != nil {
		return x.AppPictureType
	}
	return 0
}

func (x *TryUploadImageRequest) GetOriginalPicture() int32 {
	if x != nil {
		return x.OriginalPicture
	}
	return 0
}

func (x *TryUploadImageRequest) GetFileIndex() []byte {
	if x != nil {
		return x.FileIndex
	}
	return nil
}

func (x *TryUploadImageRequest) GetDstUin() int64 {
	if x != nil {
		return x.DstUin
	}
	return 0
}

func (x *TryUploadImageRequest) GetServerUpload() int32 {
	if x != nil {
		return x.ServerUpload
	}
	return 0
}

func (x *TryUploadImageRequest) GetTransferUrl() string {
	if x != nil {
		return x.TransferUrl
	}
	return ""
}

type TryUploadImageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId1      int64                        `protobuf:"varint,1,opt,name=file_id1,json=fileId1,proto3" json:"file_id1,omitempty"`
	Result       int32                        `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	FailMessage  string                       `protobuf:"bytes,3,opt,name=fail_message,json=failMessage,proto3" json:"fail_message,omitempty"`
	FileExist    bool                         `protobuf:"varint,4,opt,name=file_exist,json=fileExist,proto3" json:"file_exist,omitempty"`
	ImgInfo      *ImageInfo                   `protobuf:"bytes,5,opt,name=img_info,json=imgInfo,proto3" json:"img_info,omitempty"`
	UploadIp     []uint32                     `protobuf:"varint,6,rep,packed,name=upload_ip,json=uploadIp,proto3" json:"upload_ip,omitempty"`
	UploadPort   []int32                      `protobuf:"varint,7,rep,packed,name=upload_port,json=uploadPort,proto3" json:"upload_port,omitempty"`
	UploadKey    []byte                       `protobuf:"bytes,8,opt,name=upload_key,json=uploadKey,proto3" json:"upload_key,omitempty"`
	FileId       int64                        `protobuf:"varint,9,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UploadOffset int64                        `protobuf:"varint,10,opt,name=upload_offset,json=uploadOffset,proto3" json:"upload_offset,omitempty"`
	BlockSize    int64                        `protobuf:"varint,11,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	NewBigChan   bool                         `protobuf:"varint,12,opt,name=new_big_chan,json=newBigChan,proto3" json:"new_big_chan,omitempty"`
	UploadIp6    []*IPv6Info                  `protobuf:"bytes,13,rep,name=upload_ip6,json=uploadIp6,proto3" json:"upload_ip6,omitempty"`
	ClientIp6    []byte                       `protobuf:"bytes,14,opt,name=client_ip6,json=clientIp6,proto3" json:"client_ip6,omitempty"`
	Info4Busi    *TryUploadImageResponse_Info `protobuf:"bytes,15,opt,name=info4busi,proto3" json:"info4busi,omitempty"`
}

func (x *TryUploadImageResponse) Reset() {
	*x = TryUploadImageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TryUploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryUploadImageResponse) ProtoMessage() {}

func (x *TryUploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryUploadImageResponse.ProtoReflect.Descriptor instead.
func (*TryUploadImageResponse) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{11}
}

func (x *TryUploadImageResponse) GetFileId1() int64 {
	if x != nil {
		return x.FileId1
	}
	return 0
}

func (x *TryUploadImageResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *TryUploadImageResponse) GetFailMessage() string {
	if x != nil {
		return x.FailMessage
	}
	return ""
}

func (x *TryUploadImageResponse) GetFileExist() bool {
	if x != nil {
		return x.FileExist
	}
	return false
}

func (x *TryUploadImageResponse) GetImgInfo() *ImageInfo {
	if x != nil {
		return x.ImgInfo
	}
	return nil
}

func (x *TryUploadImageResponse) GetUploadIp() []uint32 {
	if x != nil {
		return x.UploadIp
	}
	return nil
}

func (x *TryUploadImageResponse) GetUploadPort() []int32 {
	if x != nil {
		return x.UploadPort
	}
	return nil
}

func (x *TryUploadImageResponse) GetUploadKey() []byte {
	if x != nil {
		return x.UploadKey
	}
	return nil
}

func (x *TryUploadImageResponse) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *TryUploadImageResponse) GetUploadOffset() int64 {
	if x != nil {
		return x.UploadOffset
	}
	return 0
}

func (x *TryUploadImageResponse) GetBlockSize() int64 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *TryUploadImageResponse) GetNewBigChan() bool {
	if x != nil {
		return x.NewBigChan
	}
	return false
}

func (x *TryUploadImageResponse) GetUploadIp6() []*IPv6Info {
	if x != nil {
		return x.UploadIp6
	}
	return nil
}

func (x *TryUploadImageResponse) GetClientIp6() []byte {
	if x != nil {
		return x.ClientIp6
	}
	return nil
}

func (x *TryUploadImageResponse) GetInfo4Busi() *TryUploadImageResponse_Info {
	if x != nil {
		return x.Info4Busi
	}
	return nil
}

type TryUploadPTTRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TryUploadPTTRequest) Reset() {
	*x = TryUploadPTTRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TryUploadPTTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryUploadPTTRequest) ProtoMessage() {}

func (x *TryUploadPTTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryUploadPTTRequest.ProtoReflect.Descriptor instead.
func (*TryUploadPTTRequest) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{12}
}

type TryUploadPTTResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TryUploadPTTResponse) Reset() {
	*x = TryUploadPTTResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TryUploadPTTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryUploadPTTResponse) ProtoMessage() {}

func (x *TryUploadPTTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryUploadPTTResponse.ProtoReflect.Descriptor instead.
func (*TryUploadPTTResponse) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{13}
}

type TryUploadImageResponse_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DownDomain      string `protobuf:"bytes,1,opt,name=down_domain,json=downDomain,proto3" json:"down_domain,omitempty"`
	ThumbDownUrl    string `protobuf:"bytes,2,opt,name=thumb_down_url,json=thumbDownUrl,proto3" json:"thumb_down_url,omitempty"`
	OriginalDownUrl string `protobuf:"bytes,3,opt,name=original_down_url,json=originalDownUrl,proto3" json:"original_down_url,omitempty"`
	BigDownUrl      string `protobuf:"bytes,4,opt,name=big_down_url,json=bigDownUrl,proto3" json:"big_down_url,omitempty"`
	FileResouceId   string `protobuf:"bytes,5,opt,name=file_resouce_id,json=fileResouceId,proto3" json:"file_resouce_id,omitempty"`
}

func (x *TryUploadImageResponse_Info) Reset() {
	*x = TryUploadImageResponse_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmd_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TryUploadImageResponse_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryUploadImageResponse_Info) ProtoMessage() {}

func (x *TryUploadImageResponse_Info) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryUploadImageResponse_Info.ProtoReflect.Descriptor instead.
func (*TryUploadImageResponse_Info) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{11, 0}
}

func (x *TryUploadImageResponse_Info) GetDownDomain() string {
	if x != nil {
		return x.DownDomain
	}
	return ""
}

func (x *TryUploadImageResponse_Info) GetThumbDownUrl() string {
	if x != nil {
		return x.ThumbDownUrl
	}
	return ""
}

func (x *TryUploadImageResponse_Info) GetOriginalDownUrl() string {
	if x != nil {
		return x.OriginalDownUrl
	}
	return ""
}

func (x *TryUploadImageResponse_Info) GetBigDownUrl() string {
	if x != nil {
		return x.BigDownUrl
	}
	return ""
}

func (x *TryUploadImageResponse_Info) GetFileResouceId() string {
	if x != nil {
		return x.FileResouceId
	}
	return ""
}

var File_cmd_proto protoreflect.FileDescriptor

var file_cmd_proto_rawDesc = []byte{
	0x0a, 0x09, 0x63, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9f, 0x03, 0x0a, 0x10,
	0x43, 0x6d, 0x64, 0x30, 0x78, 0x30, 0x33, 0x38, 0x38, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x6e, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73,
	0x75, 0x62, 0x5f, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x75,
	0x62, 0x43, 0x6d, 0x64, 0x12, 0x40, 0x0a, 0x10, 0x74, 0x72, 0x79, 0x5f, 0x75, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x54, 0x72, 0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0e, 0x74, 0x72, 0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x0b, 0x67, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12,
	0x3a, 0x0a, 0x0e, 0x74, 0x72, 0x79, 0x5f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x70, 0x74,
	0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x54, 0x72, 0x79, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x50, 0x54, 0x54, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0c, 0x74,
	0x72, 0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x74, 0x74, 0x12, 0x31, 0x0a, 0x0b, 0x67,
	0x65, 0x74, 0x5f, 0x70, 0x74, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x54, 0x54, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x09, 0x67, 0x65, 0x74, 0x50, 0x74, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x30, 0x0a,
	0x09, 0x64, 0x65, 0x6c, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x64, 0x65, 0x6c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xea, 0x02,
	0x0a, 0x11, 0x43, 0x6d, 0x64, 0x30, 0x78, 0x30, 0x33, 0x38, 0x38, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x70,
	0x12, 0x17, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x5f, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x73, 0x75, 0x62, 0x43, 0x6d, 0x64, 0x12, 0x41, 0x0a, 0x10, 0x74, 0x72, 0x79,
	0x5f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x54, 0x72, 0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0e, 0x74, 0x72,
	0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x0d,
	0x67, 0x65, 0x74, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x52,
	0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0b, 0x67, 0x65, 0x74, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x3b, 0x0a, 0x0e, 0x74, 0x72, 0x79, 0x5f, 0x75, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x70, 0x74, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x54, 0x72, 0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x54, 0x54, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x74, 0x72, 0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x50, 0x74, 0x74, 0x12, 0x32, 0x0a, 0x0b, 0x67, 0x65, 0x74, 0x5f, 0x70, 0x74, 0x74, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x54,
	0x54, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x09, 0x67, 0x65,
	0x74, 0x50, 0x74, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x31, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x5f, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x08, 0x64, 0x65, 0x6c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x15, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x54, 0x54, 0x55, 0x52,
	0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50,
	0x54, 0x54, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xa0, 0x01,
	0x0a, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x6d, 0x64, 0x35, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x66,
	0x69, 0x6c, 0x65, 0x4d, 0x64, 0x35, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12,
	0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x22, 0x30, 0x0a, 0x08, 0x49, 0x50, 0x76, 0x36, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x70, 0x36, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x69, 0x70, 0x36, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x22, 0x99, 0x05, 0x0a, 0x15, 0x54, 0x72, 0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73,
	0x72, 0x63, 0x5f, 0x75, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x72,
	0x63, 0x55, 0x69, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6d, 0x64, 0x35, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x66, 0x69, 0x6c, 0x65, 0x4d, 0x64, 0x35, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x72, 0x63, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x72, 0x63, 0x54, 0x65, 0x72, 0x6d, 0x12, 0x23, 0x0a, 0x0d,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x75, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x62, 0x75, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x69,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12,
	0x25, 0x0a, 0x0e, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x69,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19,
	0x0a, 0x08, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x70, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x70, 0x12, 0x28, 0x0a, 0x10, 0x61, 0x70, 0x70,
	0x5f, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0e, 0x61, 0x70, 0x70, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f,
	0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x11, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x17, 0x0a,
	0x07, 0x64, 0x73, 0x74, 0x5f, 0x75, 0x69, 0x6e, 0x18, 0x12, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x64, 0x73, 0x74, 0x55, 0x69, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x13, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x14, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x22, 0xdb,
	0x05, 0x0a, 0x16, 0x54, 0x72, 0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x69, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x66, 0x69, 0x6c,
	0x65, 0x49, 0x64, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x21, 0x0a, 0x0c,
	0x66, 0x61, 0x69, 0x6c, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x66, 0x61, 0x69, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x65, 0x78, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x78, 0x69, 0x73, 0x74, 0x12, 0x25,
	0x0a, 0x08, 0x69, 0x6d, 0x67, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x69, 0x6d,
	0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f,
	0x69, 0x70, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x49, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50,
	0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4b,
	0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x75,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x20, 0x0a, 0x0c, 0x6e, 0x65, 0x77, 0x5f, 0x62, 0x69, 0x67, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x42, 0x69, 0x67, 0x43, 0x68, 0x61,
	0x6e, 0x12, 0x28, 0x0a, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x70, 0x36, 0x18,
	0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x49, 0x50, 0x76, 0x36, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x09, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x70, 0x36, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x70, 0x36, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x70, 0x36, 0x12, 0x3a, 0x0a, 0x09, 0x69, 0x6e,
	0x66, 0x6f, 0x34, 0x62, 0x75, 0x73, 0x69, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x54, 0x72, 0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x69, 0x6e, 0x66,
	0x6f, 0x34, 0x62, 0x75, 0x73, 0x69, 0x1a, 0xc3, 0x01, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x1f, 0x0a, 0x0b, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x77, 0x6e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x12, 0x24, 0x0a, 0x0e, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x44,
	0x6f, 0x77, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x2a, 0x0a, 0x11, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x61, 0x6c, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x44, 0x6f, 0x77, 0x6e, 0x55,
	0x72, 0x6c, 0x12, 0x20, 0x0a, 0x0c, 0x62, 0x69, 0x67, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x69, 0x67, 0x44, 0x6f, 0x77,
	0x6e, 0x55, 0x72, 0x6c, 0x12, 0x26, 0x0a, 0x0f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x63, 0x65, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x13,
	0x54, 0x72, 0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x54, 0x54, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x54, 0x72, 0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x50, 0x54, 0x54, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmd_proto_rawDescOnce sync.Once
	file_cmd_proto_rawDescData = file_cmd_proto_rawDesc
)

func file_cmd_proto_rawDescGZIP() []byte {
	file_cmd_proto_rawDescOnce.Do(func() {
		file_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmd_proto_rawDescData)
	})
	return file_cmd_proto_rawDescData
}

var file_cmd_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_cmd_proto_goTypes = []interface{}{
	(*Cmd0X0388Request)(nil),            // 0: Cmd0x0388Request
	(*Cmd0X0388Response)(nil),           // 1: Cmd0x0388Response
	(*DeleteImageRequest)(nil),          // 2: DeleteImageRequest
	(*DeleteImageResponse)(nil),         // 3: DeleteImageResponse
	(*GetImageURLRequest)(nil),          // 4: GetImageURLRequest
	(*GetImageURLResponse)(nil),         // 5: GetImageURLResponse
	(*GetPTTURLRequest)(nil),            // 6: GetPTTURLRequest
	(*GetPTTURLResponse)(nil),           // 7: GetPTTURLResponse
	(*ImageInfo)(nil),                   // 8: ImageInfo
	(*IPv6Info)(nil),                    // 9: IPv6Info
	(*TryUploadImageRequest)(nil),       // 10: TryUploadImageRequest
	(*TryUploadImageResponse)(nil),      // 11: TryUploadImageResponse
	(*TryUploadPTTRequest)(nil),         // 12: TryUploadPTTRequest
	(*TryUploadPTTResponse)(nil),        // 13: TryUploadPTTResponse
	(*TryUploadImageResponse_Info)(nil), // 14: TryUploadImageResponse.Info
}
var file_cmd_proto_depIdxs = []int32{
	10, // 0: Cmd0x0388Request.try_upload_image:type_name -> TryUploadImageRequest
	4,  // 1: Cmd0x0388Request.get_image_url:type_name -> GetImageURLRequest
	12, // 2: Cmd0x0388Request.try_upload_ptt:type_name -> TryUploadPTTRequest
	6,  // 3: Cmd0x0388Request.get_ptt_url:type_name -> GetPTTURLRequest
	2,  // 4: Cmd0x0388Request.del_image:type_name -> DeleteImageRequest
	11, // 5: Cmd0x0388Response.try_upload_image:type_name -> TryUploadImageResponse
	5,  // 6: Cmd0x0388Response.get_image_url:type_name -> GetImageURLResponse
	13, // 7: Cmd0x0388Response.try_upload_ptt:type_name -> TryUploadPTTResponse
	7,  // 8: Cmd0x0388Response.get_ptt_url:type_name -> GetPTTURLResponse
	3,  // 9: Cmd0x0388Response.del_image:type_name -> DeleteImageResponse
	8,  // 10: TryUploadImageResponse.img_info:type_name -> ImageInfo
	9,  // 11: TryUploadImageResponse.upload_ip6:type_name -> IPv6Info
	14, // 12: TryUploadImageResponse.info4busi:type_name -> TryUploadImageResponse.Info
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_cmd_proto_init() }
func file_cmd_proto_init() {
	if File_cmd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cmd0X0388Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cmd0X0388Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteImageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetImageURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetImageURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPTTURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPTTURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPv6Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TryUploadImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TryUploadImageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TryUploadPTTRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TryUploadPTTResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmd_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TryUploadImageResponse_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_proto_goTypes,
		DependencyIndexes: file_cmd_proto_depIdxs,
		MessageInfos:      file_cmd_proto_msgTypes,
	}.Build()
	File_cmd_proto = out.File
	file_cmd_proto_rawDesc = nil
	file_cmd_proto_goTypes = nil
	file_cmd_proto_depIdxs = nil
}
