// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: device_report.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bootloader   []byte `protobuf:"bytes,10,opt,name=bootloader,proto3" json:"bootloader,omitempty"`
	ProcVersion  []byte `protobuf:"bytes,18,opt,name=procVersion,proto3" json:"procVersion,omitempty"`
	Codename     []byte `protobuf:"bytes,26,opt,name=codename,proto3" json:"codename,omitempty"`
	Incremental  []byte `protobuf:"bytes,34,opt,name=incremental,proto3" json:"incremental,omitempty"`
	Fingerprint  []byte `protobuf:"bytes,42,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	BootId       []byte `protobuf:"bytes,50,opt,name=bootId,proto3" json:"bootId,omitempty"`
	AndroidId    []byte `protobuf:"bytes,58,opt,name=androidId,proto3" json:"androidId,omitempty"`
	Baseband     []byte `protobuf:"bytes,66,opt,name=baseband,proto3" json:"baseband,omitempty"`
	InnerVersion []byte `protobuf:"bytes,74,opt,name=innerVersion,proto3" json:"innerVersion,omitempty"`
}

func (x *DeviceReport) Reset() {
	*x = DeviceReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_report_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceReport) ProtoMessage() {}

func (x *DeviceReport) ProtoReflect() protoreflect.Message {
	mi := &file_device_report_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceReport.ProtoReflect.Descriptor instead.
func (*DeviceReport) Descriptor() ([]byte, []int) {
	return file_device_report_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceReport) GetBootloader() []byte {
	if x != nil {
		return x.Bootloader
	}
	return nil
}

func (x *DeviceReport) GetProcVersion() []byte {
	if x != nil {
		return x.ProcVersion
	}
	return nil
}

func (x *DeviceReport) GetCodename() []byte {
	if x != nil {
		return x.Codename
	}
	return nil
}

func (x *DeviceReport) GetIncremental() []byte {
	if x != nil {
		return x.Incremental
	}
	return nil
}

func (x *DeviceReport) GetFingerprint() []byte {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

func (x *DeviceReport) GetBootId() []byte {
	if x != nil {
		return x.BootId
	}
	return nil
}

func (x *DeviceReport) GetAndroidId() []byte {
	if x != nil {
		return x.AndroidId
	}
	return nil
}

func (x *DeviceReport) GetBaseband() []byte {
	if x != nil {
		return x.Baseband
	}
	return nil
}

func (x *DeviceReport) GetInnerVersion() []byte {
	if x != nil {
		return x.InnerVersion
	}
	return nil
}

var File_device_report_proto protoreflect.FileDescriptor

var file_device_report_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa6, 0x02, 0x0a, 0x0c, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x74, 0x6c, 0x6f,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x62, 0x6f, 0x6f, 0x74,
	0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x70, 0x72, 0x6f,
	0x63, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x64, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x1a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6f, 0x64, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x61, 0x6c, 0x18, 0x22, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x69, 0x6e, 0x63, 0x72, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72,
	0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x2a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x66, 0x69, 0x6e,
	0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x6f, 0x74,
	0x49, 0x64, 0x18, 0x32, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x74, 0x49, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x49, 0x64, 0x18, 0x3a, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x62, 0x61, 0x73, 0x65, 0x62, 0x61, 0x6e, 0x64, 0x18, 0x42, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x62, 0x61, 0x6e, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x4a, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0c, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x07,
	0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_device_report_proto_rawDescOnce sync.Once
	file_device_report_proto_rawDescData = file_device_report_proto_rawDesc
)

func file_device_report_proto_rawDescGZIP() []byte {
	file_device_report_proto_rawDescOnce.Do(func() {
		file_device_report_proto_rawDescData = protoimpl.X.CompressGZIP(file_device_report_proto_rawDescData)
	})
	return file_device_report_proto_rawDescData
}

var file_device_report_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_device_report_proto_goTypes = []interface{}{
	(*DeviceReport)(nil), // 0: DeviceReport
}
var file_device_report_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_device_report_proto_init() }
func file_device_report_proto_init() {
	if File_device_report_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_device_report_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_device_report_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_device_report_proto_goTypes,
		DependencyIndexes: file_device_report_proto_depIdxs,
		MessageInfos:      file_device_report_proto_msgTypes,
	}.Build()
	File_device_report_proto = out.File
	file_device_report_proto_rawDesc = nil
	file_device_report_proto_goTypes = nil
	file_device_report_proto_depIdxs = nil
}
