// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: online_push.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnlinePush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnlinePush) Reset() {
	*x = OnlinePush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_push_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlinePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlinePush) ProtoMessage() {}

func (x *OnlinePush) ProtoReflect() protoreflect.Message {
	mi := &file_online_push_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlinePush.ProtoReflect.Descriptor instead.
func (*OnlinePush) Descriptor() ([]byte, []int) {
	return file_online_push_proto_rawDescGZIP(), []int{0}
}

// msg_onlinepush
type OnlinePush_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message     *MessageCommon_Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                             // "msg"
	ServerIp    uint32                 `protobuf:"varint,2,opt,name=server_ip,json=serverIp,proto3" json:"server_ip,omitempty"`          // "svrip"
	PushToken   []byte                 `protobuf:"bytes,3,opt,name=push_token,json=pushToken,proto3" json:"push_token,omitempty"`        // "bytes_push_token"
	PingFlag    uint32                 `protobuf:"varint,4,opt,name=ping_flag,json=pingFlag,proto3" json:"ping_flag,omitempty"`          // "ping_flag"
	GeneralFlag uint32                 `protobuf:"varint,9,opt,name=general_flag,json=generalFlag,proto3" json:"general_flag,omitempty"` // "uint32_general_flag"
	BindUin     uint64                 `protobuf:"varint,10,opt,name=bind_uin,json=bindUin,proto3" json:"bind_uin,omitempty"`            // "uint64_bind_uin"
}

func (x *OnlinePush_Message) Reset() {
	*x = OnlinePush_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_push_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlinePush_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlinePush_Message) ProtoMessage() {}

func (x *OnlinePush_Message) ProtoReflect() protoreflect.Message {
	mi := &file_online_push_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlinePush_Message.ProtoReflect.Descriptor instead.
func (*OnlinePush_Message) Descriptor() ([]byte, []int) {
	return file_online_push_proto_rawDescGZIP(), []int{0, 0}
}

func (x *OnlinePush_Message) GetMessage() *MessageCommon_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *OnlinePush_Message) GetServerIp() uint32 {
	if x != nil {
		return x.ServerIp
	}
	return 0
}

func (x *OnlinePush_Message) GetPushToken() []byte {
	if x != nil {
		return x.PushToken
	}
	return nil
}

func (x *OnlinePush_Message) GetPingFlag() uint32 {
	if x != nil {
		return x.PingFlag
	}
	return 0
}

func (x *OnlinePush_Message) GetGeneralFlag() uint32 {
	if x != nil {
		return x.GeneralFlag
	}
	return 0
}

func (x *OnlinePush_Message) GetBindUin() uint64 {
	if x != nil {
		return x.BindUin
	}
	return 0
}

// OnlinePushTrans
type OnlinePush_Transport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromUin           uint64                           `protobuf:"varint,1,opt,name=from_uin,json=fromUin,proto3" json:"from_uin,omitempty"`                                   // "from_uin"
	ToUin             uint64                           `protobuf:"varint,2,opt,name=to_uin,json=toUin,proto3" json:"to_uin,omitempty"`                                         // "to_uin"
	MessageType       uint32                           `protobuf:"varint,3,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`                       // "msg_type"
	MessageSubtype    uint32                           `protobuf:"varint,4,opt,name=message_subtype,json=messageSubtype,proto3" json:"message_subtype,omitempty"`              // "msg_subtype"
	MessageSeq        uint32                           `protobuf:"varint,5,opt,name=message_seq,json=messageSeq,proto3" json:"message_seq,omitempty"`                          // "msg_seq"
	MessageUid        uint64                           `protobuf:"varint,6,opt,name=message_uid,json=messageUid,proto3" json:"message_uid,omitempty"`                          // "msg_uid"
	MessageTime       uint32                           `protobuf:"varint,7,opt,name=message_time,json=messageTime,proto3" json:"message_time,omitempty"`                       // "msg_time"
	RealMessageTime   uint32                           `protobuf:"varint,8,opt,name=real_message_time,json=realMessageTime,proto3" json:"real_message_time,omitempty"`         // "real_msg_time"
	NickName          string                           `protobuf:"bytes,9,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`                                 // "nick_name"
	MessageData       []byte                           `protobuf:"bytes,10,opt,name=message_data,json=messageData,proto3" json:"message_data,omitempty"`                       // "msg_data"
	ServerIp          uint32                           `protobuf:"varint,11,opt,name=server_ip,json=serverIp,proto3" json:"server_ip,omitempty"`                               // "svr_ip"
	ExtraGroupKeyInfo *MessageCommon_ExtraGroupKeyInfo `protobuf:"bytes,12,opt,name=extra_group_key_info,json=extraGroupKeyInfo,proto3" json:"extra_group_key_info,omitempty"` // "ext_group_key_info"
	GeneralFlag       uint32                           `protobuf:"varint,17,opt,name=general_flag,json=generalFlag,proto3" json:"general_flag,omitempty"`                      // "uint32_general_flag"
}

func (x *OnlinePush_Transport) Reset() {
	*x = OnlinePush_Transport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_push_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlinePush_Transport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlinePush_Transport) ProtoMessage() {}

func (x *OnlinePush_Transport) ProtoReflect() protoreflect.Message {
	mi := &file_online_push_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlinePush_Transport.ProtoReflect.Descriptor instead.
func (*OnlinePush_Transport) Descriptor() ([]byte, []int) {
	return file_online_push_proto_rawDescGZIP(), []int{0, 1}
}

func (x *OnlinePush_Transport) GetFromUin() uint64 {
	if x != nil {
		return x.FromUin
	}
	return 0
}

func (x *OnlinePush_Transport) GetToUin() uint64 {
	if x != nil {
		return x.ToUin
	}
	return 0
}

func (x *OnlinePush_Transport) GetMessageType() uint32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *OnlinePush_Transport) GetMessageSubtype() uint32 {
	if x != nil {
		return x.MessageSubtype
	}
	return 0
}

func (x *OnlinePush_Transport) GetMessageSeq() uint32 {
	if x != nil {
		return x.MessageSeq
	}
	return 0
}

func (x *OnlinePush_Transport) GetMessageUid() uint64 {
	if x != nil {
		return x.MessageUid
	}
	return 0
}

func (x *OnlinePush_Transport) GetMessageTime() uint32 {
	if x != nil {
		return x.MessageTime
	}
	return 0
}

func (x *OnlinePush_Transport) GetRealMessageTime() uint32 {
	if x != nil {
		return x.RealMessageTime
	}
	return 0
}

func (x *OnlinePush_Transport) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *OnlinePush_Transport) GetMessageData() []byte {
	if x != nil {
		return x.MessageData
	}
	return nil
}

func (x *OnlinePush_Transport) GetServerIp() uint32 {
	if x != nil {
		return x.ServerIp
	}
	return 0
}

func (x *OnlinePush_Transport) GetExtraGroupKeyInfo() *MessageCommon_ExtraGroupKeyInfo {
	if x != nil {
		return x.ExtraGroupKeyInfo
	}
	return nil
}

func (x *OnlinePush_Transport) GetGeneralFlag() uint32 {
	if x != nil {
		return x.GeneralFlag
	}
	return 0
}

var File_online_push_proto protoreflect.FileDescriptor

var file_online_push_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xd1, 0x05, 0x0a, 0x0a, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x75, 0x73,
	0x68, 0x1a, 0xd2, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x70, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x75, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x70, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x69, 0x6e, 0x67, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x70, 0x69, 0x6e, 0x67, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x6c, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x62,
	0x69, 0x6e, 0x64, 0x5f, 0x75, 0x69, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x62,
	0x69, 0x6e, 0x64, 0x55, 0x69, 0x6e, 0x1a, 0xed, 0x03, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x6e, 0x12,
	0x15, 0x0a, 0x06, 0x74, 0x6f, 0x5f, 0x75, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x74, 0x6f, 0x55, 0x69, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x75, 0x62, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x75, 0x62, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65,
	0x71, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x53, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x75,
	0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x55, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x72, 0x65, 0x61, 0x6c, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0f, 0x72, 0x65, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x69, 0x63, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x70,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x70,
	0x12, 0x51, 0x0a, 0x14, 0x65, 0x78, 0x74, 0x72, 0x61, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x6b, 0x65, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45,
	0x78, 0x74, 0x72, 0x61, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4b, 0x65, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x11, 0x65, 0x78, 0x74, 0x72, 0x61, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4b, 0x65, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x5f, 0x66,
	0x6c, 0x61, 0x67, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x6c, 0x46, 0x6c, 0x61, 0x67, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_online_push_proto_rawDescOnce sync.Once
	file_online_push_proto_rawDescData = file_online_push_proto_rawDesc
)

func file_online_push_proto_rawDescGZIP() []byte {
	file_online_push_proto_rawDescOnce.Do(func() {
		file_online_push_proto_rawDescData = protoimpl.X.CompressGZIP(file_online_push_proto_rawDescData)
	})
	return file_online_push_proto_rawDescData
}

var file_online_push_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_online_push_proto_goTypes = []interface{}{
	(*OnlinePush)(nil),                      // 0: OnlinePush
	(*OnlinePush_Message)(nil),              // 1: OnlinePush.Message
	(*OnlinePush_Transport)(nil),            // 2: OnlinePush.Transport
	(*MessageCommon_Message)(nil),           // 3: MessageCommon.Message
	(*MessageCommon_ExtraGroupKeyInfo)(nil), // 4: MessageCommon.ExtraGroupKeyInfo
}
var file_online_push_proto_depIdxs = []int32{
	3, // 0: OnlinePush.Message.message:type_name -> MessageCommon.Message
	4, // 1: OnlinePush.Transport.extra_group_key_info:type_name -> MessageCommon.ExtraGroupKeyInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_online_push_proto_init() }
func file_online_push_proto_init() {
	if File_online_push_proto != nil {
		return
	}
	file_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_online_push_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlinePush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_push_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlinePush_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_push_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlinePush_Transport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_online_push_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_online_push_proto_goTypes,
		DependencyIndexes: file_online_push_proto_depIdxs,
		MessageInfos:      file_online_push_proto_msgTypes,
	}.Build()
	File_online_push_proto = out.File
	file_online_push_proto_rawDesc = nil
	file_online_push_proto_goTypes = nil
	file_online_push_proto_depIdxs = nil
}
